// Pre-built Excalidraw templates converted via official converter
import { convertToExcalidrawElements } from "@excalidraw/excalidraw";

export const welcomeDiagram = convertToExcalidrawElements([
  {
    type: "rectangle",
    x: 100,
    y: 100,
    width: 340,
    height: 120,
    strokeColor: "#1d4ed8",
    backgroundColor: "#dbeafe",
    fillStyle: "solid",
    roundness: { type: 3 },
    label: {
      text: "✨ Excalidraw AI Connected!\nReady for sketching & teaching",
      fontSize: 20,
      textAlign: "center",
      verticalAlign: "middle",
    },
  },
  {
    type: "arrow",
    x: 440,
    y: 160,
    width: 120,
    height: 0,
    strokeColor: "#4f46e5",
    points: [[0, 0], [120, 0]],
    label: { text: "Explore" },
  },
  {
    type: "rectangle",
    x: 560,
    y: 100,
    width: 320,
    height: 120,
    strokeColor: "#059669",
    backgroundColor: "#d1fae5",
    fillStyle: "solid",
    roundness: { type: 3 },
    label: {
      text: "🚀 All Teaching Features Ready:\nAI, Slides, Presenter & PPT Export",
      fontSize: 18,
      textAlign: "center",
      verticalAlign: "middle",
    },
  },
]);

export const architectureTemplate = convertToExcalidrawElements([
  {
    type: "rectangle",
    x: 80,
    y: 180,
    width: 220,
    height: 100,
    strokeColor: "#2563eb",
    backgroundColor: "#eff6ff",
    fillStyle: "solid",
    roundness: { type: 3 },
    label: {
      text: "Web Client\n(React + Vite)",
      fontSize: 18,
      textAlign: "center",
      verticalAlign: "middle",
    },
  },
  {
    type: "arrow",
    x: 300,
    y: 230,
    width: 120,
    height: 0,
    strokeColor: "#64748b",
    points: [[0, 0], [120, 0]],
    label: { text: "HTTPS / REST" },
  },
  {
    type: "rectangle",
    x: 420,
    y: 180,
    width: 230,
    height: 100,
    strokeColor: "#7c3aed",
    backgroundColor: "#f5f3ff",
    fillStyle: "solid",
    roundness: { type: 3 },
    label: {
      text: "API Gateway\n(Rate Limit & Auth)",
      fontSize: 18,
      textAlign: "center",
      verticalAlign: "middle",
    },
  },
  {
    type: "arrow",
    x: 650,
    y: 230,
    width: 120,
    height: 0,
    strokeColor: "#64748b",
    points: [[0, 0], [120, 0]],
    label: { text: "SQL Query" },
  },
  {
    type: "ellipse",
    x: 770,
    y: 170,
    width: 200,
    height: 120,
    strokeColor: "#059669",
    backgroundColor: "#ecfdf5",
    fillStyle: "solid",
    label: {
      text: "Database\n(PostgreSQL Shards)",
      fontSize: 18,
      textAlign: "center",
      verticalAlign: "middle",
    },
  },
]);

export const flowchartTemplate = convertToExcalidrawElements([
  {
    type: "ellipse",
    x: 350,
    y: 70,
    width: 180,
    height: 80,
    strokeColor: "#059669",
    backgroundColor: "#d1fae5",
    fillStyle: "solid",
    label: {
      text: "Start Process",
      fontSize: 20,
      textAlign: "center",
      verticalAlign: "middle",
    },
  },
  {
    type: "arrow",
    x: 440,
    y: 150,
    width: 0,
    height: 80,
    strokeColor: "#334155",
    points: [[0, 0], [0, 80]],
  },
  {
    type: "rectangle",
    x: 320,
    y: 230,
    width: 240,
    height: 85,
    strokeColor: "#2563eb",
    backgroundColor: "#dbeafe",
    fillStyle: "solid",
    roundness: { type: 3 },
    label: {
      text: "Execute Pipeline Step",
      fontSize: 18,
      textAlign: "center",
      verticalAlign: "middle",
    },
  },
  {
    type: "arrow",
    x: 440,
    y: 315,
    width: 0,
    height: 80,
    strokeColor: "#334155",
    points: [[0, 0], [0, 80]],
  },
  {
    type: "diamond",
    x: 320,
    y: 395,
    width: 240,
    height: 120,
    strokeColor: "#d97706",
    backgroundColor: "#fef3c7",
    fillStyle: "solid",
    label: {
      text: "Pass Quality Check?",
      fontSize: 18,
      textAlign: "center",
      verticalAlign: "middle",
    },
  },
]);
